import { auth } from "@/auth";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { UsageProvider } from "@/context/UsageProvider";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<html lang="en">
			<body className={`${poppins.className} antialiased`}>
				<ThemeProvider attribute="class">
					<UsageProvider>
						<Navbar user={session?.user!} />
						{children}
						<Toaster />
					</UsageProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
